// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzxqcwwcdwyrfekkwodn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6eHFjd3djZHd5cmZla2t3b2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4MjYxMzIsImV4cCI6MjA4NzQwMjEzMn0.cHn7c9q3RxPBJth9c7QvhtW4AAeCX9CcyUrRho5IOfs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});